### ISSUE TITLE
utf8

### ISSUE THREAD

**Issue by ainthek** [michaelrhanson/jwt-js#4]
Base64url encoding the bytes of the UTF-8 representation of the JSON Claims Set

which code makes utf-8 representation of the payload ?

**Comment by michaelrhanson** [comment]
The implementation assumes that the value passed to the WebToken constructor as `objectStr` is already a valid UTF-8-encoded payload object.   All this library does is serialize, digest, and sign it.

See https://github.com/michaelrhanson/jwt-js/blob/master/tests/jsonWebTokenTest.htm for examples of how this works.
